server:
  port: 8089
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
gmall:
  jwt:
    pubKeyPath: D:\\rsa\\rsa.pub
    pribKeyPath: D:\\rsa\\rsa.pri
    secret: sf3423jsd#3$Fds32
    expire: 30
    cookieName: Gmall_TOKEN
