server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: index-route
          uri: lb://index-server
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: pms-route
          uri: lb://pms-server
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-server
          predicates:
              - Path=/sms/**
        - id: wms-route
          uri: lb://wms-server
          predicates:
            - Path=/wms/**
        - id: ums-route
          uri: lb://ums-server
          predicates:
              - Path=/ums/**
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gateway